import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";

const fontSans = FontSans({
  display: "auto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Solomon Finance",
  description: "Generated by create solomon app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${fontSans.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
